import type { User } from './users'
export type { User } from './users'

export function getUsers(): Promise<User[]> {
    return Promise.resolve([
        {
            username: 'Excepteur labore quis',
            phone: '+9-075(77',
            email: 'olX@MDHYLrGgCetmcfyNCZIBXhcwfuz.uelv',
            id: '9c5a157d-dd0c-2613-0678-f46a724f588a',
            nif: 'ea in et',
            lastName2: 'minim aute esse id quis',
            lastName: 'ex',
            firstName: 'proident in sed',
        },
        {
            id: '87fbd668-6a3d-f0fb-e418-03044279c6a3',
            lastName: 'deserunt do pariatur Lorem',
            firstName: 'Excepteur',
            lastName2: 'ut Duis dolor',
            phone: '+1-0)0(2899567+995+03(60508)1',
            nif: 'laboris ipsum cillum laborum magna',
            username: 'proident est adipisicing dolore',
            email: 'zbSS5j4U@GgbURxEOjgn.jkl',
        },
        {
            nif: 'minim pariatur velit',
            lastName: 'ullamco cupidatat voluptate eu sed',
            firstName: 'minim consequat labore ut',
            username: 'amet anim fugiat ut mollit',
            email: 'OtRRwp0jDrDJ0w@M.liv',
            id: 'c4875e9c-cd15-a756-54fb-440824c25fc7',
            lastName2: 'dolor sit',
            phone: '+68-5+036(25(+-5(4)6(1681',
        },
        {
            email: 'o1jn@Svlzz.upy',
            username: 'sint eiusmod ullamco',
            lastName: 'officia et eu qui',
            lastName2: 'dolor consequat',
            phone: '+875-625+)1778',
            id: 'd41edb5e-dd9f-cf05-9050-c83c27e653bd',
            firstName: 'anim dolor est',
            nif: 'Duis',
        },
        {
            firstName: 'occaecat',
            email: 'k8Kgr@rFyblKhJQXgUzcYlBPbGOVcmsjvlI.ky',
            username: 'consectetur in anim cupidatat consequat',
            nif: 'mollit in',
            id: '2d8db76b-d0fd-2a63-53f4-b73020d7795c',
            lastName: 'velit eu dolor ullamco',
            phone: '+207--6-16065+',
            lastName2: 'aute officia',
        },
        {
            firstName: 'irure deserunt anim',
            nif: 'qui nulla sit',
            lastName2: 'qui',
            username: 'in pariatur',
            email: 'EgJHZy@EpnVnnCqdfyGSJCEVvlVmxVvArsNW.jt',
            id: '574ca65a-7ecc-5ebf-91e0-2ca2d9876217',
            phone: '+216-8)85-)235',
            lastName: 'ut ad eu',
        },
        {
            lastName: 'mollit Lorem enim fugiat laboris',
            email: '4mmq@jTSGvLbQtoEughPJfIiid.ga',
            id: 'd1bb838e-5a80-3f5b-c23f-268cca185ad2',
            firstName: 'dolor in',
            lastName2: 'fugiat Excepteur commodo nisi aliqua',
            username: 'nostrud dolor mollit aute qui',
            nif: 'ut Ut',
            phone: '+872--54---9957',
        },
        {
            username: 'fugiat anim',
            lastName2: 'consectetur',
            lastName: 'minim consectetur qui irure officia',
            firstName: 'aliquip ipsum elit amet',
            email: 'g3xGK8uLbf0g7@TJSMhfFGrMwILlvVxJsAWmr.hkx',
            phone: '+2-+29-0600+7633()875)7866772+1',
            nif: 'eiusmod in',
            id: 'ae7d61c7-b43a-1bc7-c23d-3e4cce039166',
        },
        {
            email: 'cMseSrFHUvb@qh.wu',
            nif: 'fugiat',
            firstName: 'cupidatat labore',
            lastName: 'consectetur',
            username: 'amet ullamco sunt',
            lastName2: 'proident laborum aliquip ut',
            id: 'a38456fc-aa67-bdfe-1dc2-513b061f45ed',
            phone: '+923-43)64338612588243812)97129034',
        },
        {
            email: 'Ity35zSOUDL@KqAOsVNktIuUDVBJsUwflEjAfNOeEfC.qtbx',
            lastName: 'cupidatat incididunt sed',
            firstName: 'reprehenderit magna ullamco',
            nif: 'adipisicing irure exercitation fugiat',
            lastName2: 'nostrud velit eiusmod tempor magna',
            username: 'tempor Lorem non',
            phone: '+49-9)6++)772-)-++2-',
            id: '9b086a3a-43ca-db51-3aad-b01553073050',
        },
        {
            lastName: 'adipisicing',
            lastName2: 'ut consequat Excepteur ullamco',
            username: 'commodo',
            id: '2e807871-3d08-d19d-a3a1-d950e5c85ef8',
            nif: 'dolore',
            email: 'l4HTpXfU4BLAzF@FAoGHOckzOcVSKNiGLdmxISrJ.dw',
            firstName: 'dolore sunt anim aliquip',
            phone: '+8-1-2190)17523',
        },
        {
            firstName: 'nulla',
            phone: '+27-(8-4807--29-7(+9221+1188(',
            lastName2: 'minim sit',
            nif: 'sint non quis',
            username: 'velit dolor occaecat',
            lastName: 'et incididunt sint Excepteur deserunt',
            id: 'c88d47aa-593a-f2ab-b5d6-c3c684852553',
            email: 'p7DQOvCfsjxY1H4@jVWFSzZUtap.ujm',
        },
        {
            lastName2: 'laborum',
            username: 'culpa adipisicing eiusmod labore qui',
            nif: 'laboris deserunt in ut',
            phone: '+02-15353++3228918932',
            firstName: 'elit dolor velit in',
            id: '5db79e74-ca07-7705-1e44-dae0547dad5c',
            lastName: 'exercitation cillum non dolor officia',
            email: 'Pisuj@svgYdFBj.fd',
        },
        {
            lastName2: 'magna anim',
            email: 'U545X9feHo@lNtOyRFyXZgcBzXUOxNbpGGUMYMcYENC.kmp',
            lastName: 'eu tempor',
            phone: '+037-+509977)6709708)0288722363',
            id: '474f3ed0-044a-b166-e9d2-9a78942f0691',
            firstName: 'ut',
            nif: 'reprehenderit',
            username: 'incididunt ut',
        },
        {
            lastName: 'cillum Lorem nisi proident',
            id: '0a959511-0b79-9dc9-15eb-4b01cc3bb992',
            email: 'fA6bUwme0g0l94l@xlLfQaANiXzJxAMpaUuqcAWoxDpK.bwgk',
            nif: 'est',
            lastName2: 'tempor adipisicing consectetur',
            username: 'eu laboris sit qui occaecat',
            firstName: 'Excepteur fugiat est',
            phone: '+2-5385190115160+204411)(794-50(',
        },
        {
            lastName2: 'ut',
            id: '7892fc86-361a-0314-dd99-63de3dfa81a7',
            firstName: 'nostrud aliqua proident ut in',
            phone: '+3-25)42(1473',
            email: 'FC5@EImgkN.mmm',
            username: 'ea pariatur exercitation',
            nif: 'veniam',
            lastName: 'officia tempor irure sint',
        },
        {
            phone: '+86-304579(2712)07-',
            lastName: 'deserunt ex velit dolor',
            id: 'caab0845-1e66-c222-d2a6-79e204a0f542',
            firstName: 'do',
            username: 'in fugiat do',
            email: 'C7ijKWqgP5TVtc@sPhoxgSIzCcNZxGIWiZorBJXFPmdGdp.ihjk',
            lastName2: 'incididunt',
            nif: 'in',
        },
        {
            username: 'ullamco veniam pariatur adipisicing',
            firstName: 'Ut',
            lastName2: 'nostrud aute',
            id: '4c7cf55c-fc14-be68-c9eb-866468ea5044',
            phone: '+97-)57016618660+2+865(',
            email: 'JCtqjVwqX@krCaHnjeYFPQKEhpPKxQSWsgd.nzi',
            lastName: 'veniam cillum eu',
            nif: 'exercitation veniam sunt aliqua',
        },
        {
            phone: '+335-14',
            nif: 'sunt et',
            lastName: 'ut velit ex',
            lastName2: 'ad',
            username: 'ut',
            id: '12ebfd83-b61a-4a1f-b8b1-1ad2ea3d85b6',
            email: 'Zhl-xf@mnlsJcCnRZxR.ifbe',
            firstName: 'dolore reprehenderit in ut Lorem',
        },
        {
            email: 'LvcE6ETBPYk@pQomGGwQhWUzFJKNWSNjWrvTjMqOFY.erfm',
            id: '602fc9b8-98b3-3ab2-e0e8-9488ef30728f',
            nif: 'sed est',
            phone: '+9-780',
            firstName: 'minim',
            lastName2: 'enim Ut do minim',
            username: 'in aliqua',
            lastName: 'consequat id',
        },
        {
            firstName: 'exercitation',
            lastName2: 'nisi nostrud',
            username: 'aliqua incididunt culpa',
            nif: 'sed labore',
            id: '0ef5f668-d3f2-d50d-7427-1eca3f19d6ef',
            lastName: 'id fugiat',
            phone: '+611-8761315)(78+)8)5(97-58)415(+)(',
            email: 'YC7wuxLvvqHVbM@tdhnniUVUsjAdiaPGgeLFDUXIVWrqePMx.ko',
        },
        {
            lastName: 'ipsum',
            firstName: 'exercitation commodo id ullamco',
            lastName2: 'incididunt proident in',
            nif: 'in',
            phone: '+64-(30()79)76(9',
            email: 'sruFw7@YhozuUIXJYfxkvwYKBTu.vuo',
            username: 'incididunt ipsum',
            id: 'e8d4eda5-4abe-e571-e7ea-1cfc60d164af',
        },
        {
            email: 'hwYuclIxI31dY7@wZpahmRpoHiIsUrMDuJFfZKVpPiqx.mw',
            nif: 'laboris',
            username: 'cupidatat magna consectetur Duis velit',
            lastName2: 'eiusmod',
            phone: '+94-8-8--473-790-3-+4-0',
            firstName: 'consequat sit deserunt',
            id: '3189151b-355c-10c1-3a4d-15397aad0581',
            lastName: 'ex',
        },
        {
            phone: '+47-98265(081426)1(840',
            nif: 'dolore fugiat',
            lastName: 'velit dolore labore',
            username: 'labore',
            lastName2: 'eiusmod reprehenderit commodo et',
            firstName: 'consequat Lorem enim officia',
            id: '37ae2cf6-18da-f1de-2625-d63ef3ff9b78',
            email: 'aIUU@AHMNlAtJaaymfIFKcFsJtugg.ovti',
        },
        {
            firstName: 'sit',
            lastName2: 'laborum',
            nif: 'proident',
            email: 'n1Nrtx@CaoBruYkBfjxL.hvk',
            id: '26823a7d-4f82-2cbe-d302-6aedc3336089',
            username: 'ut magna',
            lastName: 'aute',
            phone: '+95-+58)+(6969770',
        },
        {
            email: 'D9UvQAfRM5OIDU@wmAfwdUTDOUgUutAcoK.rkiq',
            lastName: 'occaecat dolor ad voluptate',
            username: 'anim consequat',
            firstName: 'consequat aute mollit quis sunt',
            phone: '+0-30',
            id: '63465abe-3c12-ab7b-05cf-f3adeef3edce',
            nif: 'officia',
            lastName2: 'laboris ullamco in nostrud incididunt',
        },
        {
            firstName: 'est exercitation quis irure',
            email: 'd4I@xHWpUMiDnfo.wvev',
            lastName: 'voluptate ad irure sint laboris',
            nif: 'in incididunt mollit reprehenderit',
            lastName2: 'ea consectetur tempor Excepteur',
            phone: '+79-8-+9(9+1-00',
            username: 'quis laboris officia proident',
            id: '59ea89a6-c0da-6bf6-eb8c-1fbf570017d6',
        },
        {
            email: 'AbX3f431SWrx-b@JgYcqyPuyODTcqtUNoeMsMJTFKs.qy',
            firstName: 'sunt velit consequat anim in',
            username: 'amet',
            phone: '+4-+54++(978',
            nif: 'do',
            id: '94136875-0a31-e315-02e2-78a9ea7c74a8',
            lastName: 'proident Excepteur Ut',
            lastName2: 'ea do elit',
        },
        {
            lastName2: 'occaecat do',
            firstName: 'amet proident Ut Lorem culpa',
            nif: 'laborum Duis id',
            username: 'dolore Duis ad labore veniam',
            id: '31ed1b62-be92-0530-b44b-94a490402f86',
            email: 'GvJmdbMDnxI@TCQQa.kgu',
            phone: '+095-)04(47+2163)-16022379',
            lastName: 'quis reprehenderit irure',
        },
        {
            lastName2: 'consequat tempor proident',
            lastName: 'dolore officia',
            phone: '+78-96)7254-745',
            nif: 'commodo',
            email: 'oWjzkggCeNx79@SIdCeClUAZfJS.ryia',
            firstName: 'sit',
            username: 'dolor culpa occaecat officia nostrud',
            id: '83bbdf4d-0a8b-ca82-3ed5-6d16be320380',
        },
        {
            id: '072dcb69-f7f1-ae9a-d3f2-510cbd1f0ce5',
            firstName: 'et ex consequat Excepteur',
            phone: '+25-15(-190))-+-46694091',
            lastName2: 'labore ipsum',
            email: 'DzM@LzuoiZiFskGXuvKnMF.bg',
            nif: 'minim fugiat dolor',
            username: 'sunt',
            lastName: 'Excepteur irure voluptate ipsum',
        },
        {
            phone: '+8-877314)',
            nif: 'in exercitation',
            lastName2: 'Ut est consequat aliqua',
            email: 'sIEgYH-YeXf@bFOhkOr.huq',
            id: '7f3dcf36-3220-8612-aa16-c12f14759121',
            username: 'in magna et minim sunt',
            lastName: 'mollit ut aliqua',
            firstName: 'dolor pariatur id dolor Lorem',
        },
        {
            lastName: 'ut dolore',
            id: '4851f4b9-ca79-131f-e859-755f6184bdf5',
            lastName2: 'proident',
            email: 'dT4rRGwTPSL11N@xWjUlezgNTeod.gyg',
            nif: 'ipsum qui',
            phone: '+7-04880731)0946)++))+50(73',
            firstName: 'officia dolore ullamco',
            username: 'cillum sed tempor',
        },
        {
            phone: '+4-()29901(',
            nif: 'officia est',
            id: '6d28f867-3b5b-ca69-08aa-7ce3bd406a8e',
            email: 'WXk-FscQBe@WMuMUFOU.icn',
            lastName2: 'velit',
            lastName: 'mollit proident do',
            firstName: 'anim culpa ullamco occaecat qui',
            username: 'est in ut exercitation mollit',
        },
        {
            lastName: 'nostrud minim velit cillum aliqua',
            id: 'dc7c225d-95bd-b9fb-95e5-3469e4ab66df',
            lastName2: 'reprehenderit esse occaecat voluptate',
            nif: 'minim eiusmod ad',
            phone: '+249-)105722(0(5+6((',
            firstName: 'pariatur',
            username: 'occaecat quis commodo amet',
            email: '4nBR9ieXARxpK@enedobqJMEakkDTcLunMKBla.me',
        },
        {
            lastName2: 'laboris elit Ut ut',
            email: 'zANxQgW3YCgOD@q.vn',
            phone: '+709-200+',
            nif: 'quis minim amet exercitation',
            id: '244ab270-bb2d-7e28-c7df-f79ffe3d7b24',
            firstName: 'voluptate',
            username: 'irure voluptate',
            lastName: 'esse',
        },
        {
            firstName: 'laborum non',
            lastName2: 'tempor ex fugiat',
            username: 'mollit esse ex aliquip',
            phone: '+45-(+8))(+637',
            nif: 'deserunt aute elit',
            id: '41fe746c-10e3-6509-3ea2-1a502ede84e0',
            lastName: 'minim labore magna',
            email: '8uhn2EK2cQ@ellbjIwOzcLojshfanxpKAKcMZgg.yppq',
        },
        {
            nif: 'qui tempor',
            firstName: 'aute',
            email: 'W13HjPoYUUTrP@mfeBCRIGeJGmmbEHmyUjOUhkA.xr',
            id: '416c1cb7-ff1d-acf6-7abc-b4bf33a473a3',
            username: 'reprehenderit nulla quis culpa',
            lastName2: 'velit',
            lastName: 'proident qui cillum officia',
            phone: '+6-(312',
        },
        {
            id: 'aefcb242-0842-3c10-3d81-e0f3018f272b',
            nif: 'esse sed irure ut est',
            email: 'vPCUPvXl8FP@OvpsBDQVOo.wl',
            phone: '+3-6(7925854+95',
            lastName: 'dolore',
            username: 'sed in Excepteur sint magna',
            lastName2: 'cillum et consectetur ex',
            firstName: 'reprehenderit dolore nulla',
        },
        {
            username: 'Lorem labore ex',
            email: 'f4vJc-PF8TUz@PYRfrPJmooPkDzTISYRdS.aj',
            firstName: 'quis exercitation labore velit',
            lastName: 'minim',
            lastName2: 'nulla proident',
            id: '7b191f61-a8f2-b3dd-8c60-ea57ebb41211',
            phone: '+7-2)-560(070)04',
            nif: 'incididunt commodo irure dolor',
        },
        {
            phone: '+6-74-',
            id: 'e76bb7a3-7c8c-255f-b070-e20d921c6f77',
            nif: 'reprehenderit consequat non',
            firstName: 'cillum non',
            email: 'pBTSJ@QHfQvplVZUx.oqmp',
            username: 'aliqua',
            lastName: 'Ut in magna ut ea',
            lastName2: 'dolore amet adipisicing do',
        },
        {
            lastName2: 'sit',
            lastName: 'nulla sint dolore ut',
            username: 'ullamco esse irure ut',
            nif: 'et sunt',
            phone: '+198-9',
            firstName: 'et dolor irure sed reprehenderit',
            id: '31f1a82e-ea57-7127-6e35-a40551970bae',
            email: '9cgzbefHb@FjirGRIwNBwyrNpzaMilVmGLWu.mbf',
        },
        {
            lastName: 'mollit quis do laborum',
            phone: '+2-2806005177+6039)6)9+521+8006)',
            firstName: 'enim Ut Duis aute minim',
            email: 'bC0Xy@awsLd.bcw',
            id: 'b964c28b-3be7-87ce-f130-fb7ad57e8583',
            nif: 'incididunt et eu in dolor',
            lastName2: 'aute consectetur non',
            username: 'sunt dolor',
        },
        {
            email: 'mvt76F6i-dQlm8@KhckiCJHYxYFKDoJiZ.mm',
            lastName: 'culpa ut dolore',
            phone: '+2-394448377-28435577-3(937',
            lastName2: 'do sed pariatur',
            username: 'consequat do quis',
            nif: 'in amet nulla',
            id: '8250b9bb-f523-281d-497e-8846b09a63f5',
            firstName: 'occaecat consequat Lorem',
        },
        {
            lastName2: 'in ut nostrud',
            username: 'sunt laboris est',
            nif: 'occaecat esse',
            lastName: 'elit',
            id: 'b5ff694c-c8c5-2eb9-36e0-d0163080be3b',
            phone: '+202-1825(5014',
            firstName: 'nulla irure',
            email: 'cpy@FTEVHiSOtbmANfFYcvaodLT.qp',
        },
        {
            username: 'minim eu enim pariatur',
            lastName: 'ea in cupidatat nisi elit',
            lastName2: 'deserunt',
            email: 'Y-20PX1gQBOOXH@ZPOeeKFlpWee.kfi',
            phone: '+360-1--)60+3408)(1-206(1-2425835)5',
            firstName: 'laboris ullamco tempor voluptate',
            id: 'bbc9147d-3f95-1984-2646-78e4fba63d5d',
            nif: 'commodo est sit ut',
        },
        {
            phone: '+7-5)188-+58',
            firstName: 'in exercitation voluptate quis eiusmod',
            lastName: 'consequat',
            username: 'reprehenderit Excepteur',
            email: 'J87uk9BuWxuM@FBXmqIsVEzv.icar',
            lastName2: 'elit',
            id: '0cb58714-614c-e317-e205-4e50fc708236',
            nif: 'exercitation ipsum',
        },
        {
            nif: 'do',
            lastName: 'magna amet exercitation ex',
            id: 'ba075f5c-ab20-646c-1396-5935c4d8bdec',
            lastName2: 'Duis Lorem ipsum ad',
            phone: '+765-49-12-04',
            firstName: 'pariatur',
            email: '7aQjQ9R8AwEPFW@anwVduuBOn.zuk',
            username: 'exercitation',
        },
        {
            phone: '+1-17375372927078578+',
            lastName2: 'nisi exercitation',
            nif: 'Duis amet adipisicing Lorem consequat',
            email: 'Qh1kf4D6lb@yLbImOUVzUUPl.ce',
            id: 'b2526494-30e9-33c3-6438-4dce982e012d',
            firstName: 'pariatur et',
            lastName: 'aliqua',
            username: 'cillum quis aliquip non',
        },
        {
            lastName: 'aliquip non esse Lorem adipisicing',
            id: '5775fb04-a9cc-314e-4d4a-9d13c02ffb79',
            lastName2: 'tempor dolor sunt non',
            firstName: 'et nisi eiusmod est',
            username: 'in esse sed non',
            nif: 'pariatur enim velit',
            email: 'UlSJDFO@FSaTlgUty.gcz',
            phone: '+148-1252(1953794778478(-)+6',
        },
        {
            id: '3461e914-3574-65cf-d247-0087ac94b05d',
            phone: '+769-081820)5101(3573(',
            lastName2: 'labore eu',
            lastName: 'nulla',
            firstName: 'qui sunt reprehenderit ut nisi',
            nif: 'magna Ut dolor dolore sit',
            email: 'SEt3W@iOsxHQJLyKvXc.wc',
            username: 'tempor et ut nostrud',
        },
        {
            id: 'aadfca98-5398-828b-a424-dadb6bb3478d',
            phone: '+42-4-403)+23',
            lastName2: 'Duis ut nostrud fugiat',
            lastName: 'ex consequat velit do',
            username: 'ut nulla proident',
            email: 'kOPjRS5puPs6@DdBusXRxWMGjEquosWuKc.phpd',
            nif: 'ex nostrud mollit quis',
            firstName: 'in esse pariatur adipisicing',
        },
        {
            lastName2: 'mollit dolore',
            id: 'ec027f3a-1d49-1d9d-cf67-b67720014482',
            lastName: 'aliquip',
            username: 'magna dolor in aute',
            phone: '+5-19(92(13)2197++(37138656-2)',
            email: 'AZlPfP3jGI@frivIUhvrfyfIsHNtMOPdZGKoJIDyp.wtxu',
            firstName: 'Lorem eiusmod eu',
            nif: 'qui irure labore',
        },
        {
            username: 'exercitation',
            phone: '+7-0826)84468)))()5126',
            nif: 'esse',
            email: 'kWR7JUHB@YFWkKDvOXbniOmZpCGlMTQSRkQmIaM.ivw',
            id: 'b2e7c483-9c7f-366f-6617-11efb30bda83',
            lastName: 'dolor exercitation incididunt',
            lastName2: 'ipsum reprehenderit id incididunt',
            firstName: 'non',
        },
        {
            lastName2: 'sint ea sit commodo labore',
            lastName: 'non deserunt',
            username: 'in enim occaecat est',
            firstName: 'consequat exercitation voluptate',
            nif: 'proident aute esse aliqua',
            phone: '+8-98(694-+-38-)5',
            id: 'bc875d6a-913b-b6ae-ec51-1d9a2fc59a7a',
            email: 'nyZ3IeNm@HCvbMbcHttXU.pq',
        },
        {
            lastName: 'labore tempor proident ipsum veniam',
            lastName2: 'consectetur',
            phone: '+338-+1-+568-769-6-12997)1)40)724',
            nif: 'id in dolor esse',
            id: 'bf3670c5-7741-5b82-5bb3-606398621d98',
            username: 'nulla',
            email: '1JqkfwF@HyHDuRUCDUTRATfGJIYjnenZeFK.il',
            firstName: 'exercitation et fugiat nostrud voluptate',
        },
        {
            phone: '+1-7-+98-6-40(5871530497',
            lastName2: 'tempor dolore mollit Excepteur',
            id: '51be115b-3bdf-5d1b-9979-47d01e36ede9',
            email: 'HldCk2lJ-i6S@OGtLagNBUUjZIzhOn.sy',
            nif: 'Excepteur qui',
            username: 'nisi ut commodo',
            lastName: 'in magna dolor sint',
            firstName: 'aliqua',
        },
        {
            firstName: 'incididunt',
            id: '461015b7-c324-436a-259f-34bd466438b5',
            lastName2: 'minim esse',
            phone: '+27--6-19332-0)(+4)93-79+(9-',
            email: 'BdgNXZV7y@NcCbjISVGxAhAOIynEEhiL.eq',
            username: 'et voluptate ea qui aute',
            lastName: 'velit',
            nif: 'labore adipisicing non',
        },
        {
            phone: '+203-233990-85299)5',
            lastName: 'amet',
            id: 'a6966d3d-a56b-54bc-5ef0-c8e79ff350f7',
            username: 'quis sed fugiat',
            lastName2: 'id eiusmod veniam anim',
            firstName: 'officia ut irure enim ullamco',
            email: 'Epr-kqoJx@KOiOFyeZHWTErutiDoNFP.kju',
            nif: 'labore cillum sit minim id',
        },
        {
            username: 'commodo Excepteur',
            nif: 'eiusmod sed',
            email: '7fdWDGSbsrB@wvnfmAaaWJkeoJakzOMLbHJSnHTxLQGIV.wbg',
            lastName: 'culpa magna in laboris tempor',
            phone: '+1-5259809950-(3932557203069',
            lastName2: 'ex',
            id: '6358d085-cc54-c6c6-2e9e-7d16b50d8a9d',
            firstName: 'Ut irure',
        },
        {
            lastName2: 'sint commodo',
            phone: '+884-1+-(21',
            username: 'ut enim incididunt',
            nif: 'amet deserunt quis',
            email: 'y0vnEA5YDm8@VmOYncXaIsLqdDcFRbAtmeqHjAQDcig.oc',
            firstName: 'elit irure',
            lastName: 'cupidatat',
            id: '188e22c5-43af-f82a-8544-e4246650bab0',
        },
        {
            nif: 'mollit Excepteur sed exercitation',
            email: 'N4z@PtYJCeuyfcuctheFlaiF.dktb',
            firstName: 'do nostrud incididunt aliqua',
            id: '631e5481-7bf3-c161-ffc8-dd3ae9244d9b',
            lastName2: 'ut aliquip fugiat sed',
            phone: '+9-33285+20)+073(44-+-',
            username: 'veniam ex reprehenderit consequat',
            lastName: 'sed qui ad eiusmod aute',
        },
        {
            lastName2: 'cupidatat voluptate tempor',
            username: 'ipsum',
            id: '730f1480-f266-bd97-5b12-5930b9db01c3',
            phone: '+83--)-429933930)9+05()(',
            email: 'mCNAzo3q0c@ZYXbIImyDpUtKoTKyUzquLqkZtP.cyvz',
            firstName: 'eu',
            lastName: 'aliqua consequat',
            nif: 'occaecat ullamco consequat',
        },
        {
            phone: '+2-680+-(',
            lastName: 'voluptate enim et',
            firstName: 'amet voluptate ipsum ad',
            username: 'qui cillum enim',
            email: 'rO23f@n.xn',
            lastName2: 'deserunt',
            nif: 'do cillum commodo',
            id: '43854d45-1097-fd1b-a002-8ff2c35b6745',
        },
        {
            email: '4vWSnMKdDT2@dzAFjnRlZmH.vb',
            lastName: 'quis consectetur reprehenderit ut',
            id: '70b7ce4b-79b5-e072-76c1-f1f101293716',
            nif: 'sunt commodo',
            username: 'veniam in Ut',
            firstName: 'nisi eiusmod aliquip velit',
            lastName2: 'sunt proident',
            phone: '+0-65+)6)+0518859(30+',
        },
        {
            lastName2: 'in et',
            lastName: 'sed magna eu Ut irure',
            id: '02c924a6-33b3-09bf-b05a-a82ec1a7e289',
            username: 'dolore ut aliqua',
            email: 'Yjy75olr9Ti@QFRgUYtSAcmHOGO.mno',
            phone: '+149-43()962-88++-)4)25-7',
            nif: 'dolor sed cillum',
            firstName: 'eiusmod adipisicing ipsum consectetur do',
        },
        {
            nif: 'velit proident id deserunt',
            username: 'ad eu officia',
            lastName: 'nostrud elit quis deserunt',
            id: '993e6924-be23-72d2-9492-bb914d551593',
            lastName2: 'deserunt voluptate sint est enim',
            phone: '+2-42+-(78070188))(',
            email: 'ZI2snMm@RQngzpGQJgbPVNzcXnuGsXIcIIkg.dhfl',
            firstName: 'anim eiusmod laboris esse',
        },
        {
            lastName2: 'Excepteur ipsum reprehenderit aliqua',
            lastName: 'esse',
            nif: 'ex sint occaecat',
            firstName: 'anim',
            id: '86949d68-55d7-f403-ce40-16c192388d23',
            email: '5TiKQJPX@PRdxCAsvECmV.ix',
            phone: '+024-7-)08424(045',
            username: 'velit laboris culpa nulla tempor',
        },
        {
            id: '4d0d1822-9bfd-8c7d-170f-0265f9ae80b1',
            lastName: 'consectetur ipsum',
            username: 'adipisicing eu ullamco sit',
            email: 'HR9tf7UeMk@mEBnSerrNaoGQTofiBrVNWJGmXSJTfeu.ltq',
            phone: '+17-546(520)9239(6',
            nif: 'nostrud magna',
            lastName2: 'eu non nisi enim quis',
            firstName: 'dolore',
        },
        {
            email: 'Rzoj3vXdt0OKT@ORWzsSGXDhbnV.toyx',
            id: 'f5f6037b-7ad5-806c-5f13-d73aec785164',
            nif: 'amet Ut commodo do',
            firstName: 'tempor dolor',
            lastName: 'in',
            lastName2: 'dolor ad Duis',
            phone: '+6-55+)697619))0397953942++4-87',
            username: 'in aliquip exercitation',
        },
        {
            email: 'phuZ@xjoo.dq',
            username: 'quis',
            nif: 'et est dolor',
            lastName2: 'ipsum voluptate id',
            lastName: 'incididunt anim',
            id: 'f99ba580-90bf-1fe4-d1f3-84a285528681',
            phone: '+7-27207-(24))6(2)',
            firstName: 'ullamco dolor in adipisicing tempor',
        },
        {
            lastName: 'deserunt',
            id: 'a9d9e809-294b-4a87-51d8-cedf26bfa068',
            phone: '+15-+)629-7)87--',
            firstName: 'ullamco Excepteur',
            username: 'Ut',
            nif: 'voluptate aliquip incididunt cupidatat',
            lastName2: 'ad quis id adipisicing',
            email: '4vm-tRm@CremPKpiRRXgPwQwNqsbepWY.jt',
        },
        {
            lastName: 'occaecat reprehenderit',
            phone: '+63-877++-+944-17-43680++++5+3',
            firstName: 'ullamco',
            username: 'occaecat',
            id: 'd546c91f-e0b8-bac0-76d6-0ed2e520ec71',
            nif: 'occaecat exercitation est',
            lastName2: 'aliqua dolor minim nostrud in',
            email: 'vcsfRbtXq2D7UGf@txmKeBEqkdueNi.igsd',
        },
        {
            nif: 'fugiat ad aliqua',
            id: 'd3b93dbe-4573-e7f8-5d8f-f58fd1450774',
            phone: '+81-)3+0)',
            email: 'TKc5Ap@OSqBDoFYRulokRQNnHkeeQYgsFaHmkc.liac',
            username: 'mollit ut dolor cillum',
            lastName: 'ut',
            lastName2: 'consectetur',
            firstName: 'aute quis laborum sint',
        },
        {
            email: 'J3rGpsmgEJYPo@VqgioxPOtrudsZNvIxHBfUOJhf.jiwe',
            nif: 'laboris sed est',
            lastName2: 'est fugiat ipsum nostrud',
            id: '1d6aaa1c-892e-134e-0a18-4cd67bbaf7ab',
            firstName: 'veniam non cillum',
            username: 'Ut dolor in quis',
            lastName: 'aliqua nostrud magna ut',
            phone: '+967-+4--8+0686+45(182',
        },
        {
            phone: '+98-+078+851+98397213704602',
            lastName: 'Ut',
            id: 'f00e5349-3ec3-4b2d-68c4-1e4d1cab600b',
            email: 'JsSeZ8zK@foODWbMoLyxzE.gb',
            username: 'eiusmod consequat elit sint',
            firstName: 'eiusmod labore tempor',
            nif: 'sed',
            lastName2: 'cupidatat amet incididunt sint',
        },
        {
            email: 'cx6VRSQ-yrFpK@hbGoOowVSMLOW.txuv',
            phone: '+03--7332+6)30-56+24871-7-11)86',
            lastName: 'et id velit',
            firstName: 'Lorem amet est',
            lastName2: 'pariatur laboris cillum nisi',
            nif: 'nulla magna',
            id: '037c56c1-7261-47e4-eba1-90b7683de04f',
            username: 'irure',
        },
        {
            username: 'non ut consectetur minim nisi',
            firstName: 'dolore Ut eu ut',
            id: '8737c5ab-5428-627d-8791-1db7779984fd',
            nif: 'commodo in fugiat',
            lastName2: 'in elit ut laboris enim',
            lastName: 'sed voluptate veniam',
            email: '5wTCzNq@HNo.ca',
            phone: '+2-+))-3',
        },
        {
            email: 'PYplfKOejN@njejVOZCIWNEWZ.lz',
            nif: 'ullamco',
            lastName2: 'in',
            username: 'consectetur sed',
            lastName: 'occaecat fugiat aliqua',
            phone: '+132-708923(14587-9-10)2368649(47',
            firstName: 'in exercitation commodo',
            id: '0d4739df-b635-363a-d706-70fef3a5c5d8',
        },
        {
            id: 'a45e0aa6-9280-330a-7174-9ebb472d678f',
            email: 'jJYf0@lMOtXnNjfPmIxaUDHGqTigtyhoGY.vhu',
            lastName2: 'sunt',
            nif: 'magna dolor reprehenderit nostrud',
            username: 'commodo',
            lastName: 'in commodo dolor',
            phone: '+047-)533)(-77851(597220',
            firstName: 'veniam occaecat',
        },
        {
            email: 'jjRNmJ@IsFTBKoNsWOnKAfTFELfGVRWMbAgHxcrO.lfwa',
            username: 'esse culpa',
            id: '70888518-c938-8f11-b7f3-5b59637fb211',
            firstName: 'commodo ut voluptate consequat fugiat',
            phone: '+500-6-5367(4620-62337774+-',
            lastName2: 'ea',
            nif: 'magna',
            lastName: 'elit Excepteur magna minim non',
        },
        {
            id: 'bd232a80-b499-63c0-0851-6a3dabb5ce3d',
            phone: '+2-96030)91)260-14)(8926021(93',
            nif: 'voluptate sint',
            lastName2: 'enim aliquip in minim veniam',
            email: 'Htk@FDlDqBfutWmFswnKH.mci',
            username: 'quis labore esse ipsum',
            lastName: 'laborum sed anim culpa',
            firstName: 'fugiat cillum tempor consequat id',
        },
        {
            firstName: 'proident eu deserunt ullamco',
            lastName: 'labore amet qui nostrud',
            nif: 'nulla consectetur occaecat',
            email: '9nuxD@YvqyWqlztDuOxydNsCUjJfZEztO.jum',
            phone: '+37-85253-3',
            id: 'bc906bfd-756e-a15c-73bb-b7360b429ebc',
            username: 'in dolore in',
            lastName2: 'cillum dolore et est',
        },
        {
            lastName: 'in labore',
            username: 'sit reprehenderit Lorem',
            nif: 'enim',
            firstName: 'nostrud nulla irure non magna',
            lastName2: 'ut nostrud nisi amet',
            phone: '+9-69-9482+(07++',
            id: '32ae6d04-f515-6d9f-86fe-13c9e5144d32',
            email: 'YPBN4u1UZUoo@n.wd',
        },
        {
            firstName: 'aute id',
            email: 'TbSEArSFFLDMOw@jCCmuS.dak',
            username: 'commodo incididunt ipsum sed',
            lastName: 'aliquip adipisicing non',
            phone: '+744-7-+((-+1866921(8-3223',
            lastName2: 'mollit nulla aliquip',
            id: 'fec8ec31-b00b-f4d9-7334-144cfe88d8cc',
            nif: 'Lorem ipsum Excepteur',
        },
        {
            phone: '+6-25)9120-6768',
            firstName: 'officia nulla magna',
            lastName: 'occaecat laboris elit',
            nif: 'sunt Lorem nostrud',
            id: '4bba94c5-61e9-d2db-4d90-bea9e9f9b5d6',
            username: 'ea eu minim',
            email: 'PImD@hzqLvdkwHfSolhKdEbaTIyPwQytGTELm.jea',
            lastName2: 'commodo',
        },
        {
            id: '4d934f54-160c-0567-515b-50fffb1e9ea7',
            firstName: 'ad esse nisi eiusmod',
            lastName: 'Ut',
            username: 'dolor irure proident Excepteur nulla',
            nif: 'aute non enim consequat',
            lastName2: 'enim mollit quis do',
            email: 'thjObF@RMuVutMcSJVn.sdcr',
            phone: '+6-68-8)72+006(472713(-27',
        },
        {
            lastName2: 'eiusmod',
            email: 'ISv11WV6RH17@YqncwOXJZlSrfSWNeQwZav.lscs',
            nif: 'irure cupidatat ut reprehenderit',
            id: '3be2422d-f11b-eeef-2187-79816fa26c4b',
            firstName: 'qui et',
            phone: '+4-17410)63(+5',
            username: 'in enim proident',
            lastName: 'ut Ut enim in ex',
        },
        {
            username: 'sunt',
            nif: 'sunt quis ut',
            id: 'fc4d4a8f-3d98-6c59-5782-a4dd7e18e536',
            lastName: 'aute laborum adipisicing ea dolore',
            lastName2: 'eiusmod',
            phone: '+5-0392)-28',
            email: 'lN27x@lnITxgLEVMLMKUyAIZKenDNhjlitdg.cw',
            firstName: 'Excepteur id',
        },
        {
            id: '69b47d1c-62c4-96cb-d08c-25462dfb9e09',
            lastName2: 'ullamco reprehenderit anim incididunt sed',
            lastName: 'non officia labore',
            nif: 'eu tempor in non',
            username: 'nisi eu elit',
            phone: '+46-8151(763-2014728857-9863+830',
            email: 'nFmB1p@SPdrmGoPiyEwXcUKBmpBum.ylby',
            firstName: 'culpa ullamco est commodo ut',
        },
        {
            lastName2: 'ex labore laboris veniam exercitation',
            lastName: 'dolor adipisicing ut',
            firstName: 'adipisicing aliqua',
            id: 'e0636d1a-242b-1c28-f672-403c7579546c',
            email: '7A2PMunEtV@HUcBOTE.ppka',
            username: 'nulla dolor sunt in',
            nif: 'cupidatat deserunt quis dolore',
            phone: '+1-+(9+',
        },
        {
            firstName: 'sint',
            lastName2: 'Ut commodo do magna velit',
            username: 'aliqua nulla',
            id: '351c81ef-d185-4ac3-a3d3-b59cf028ba37',
            phone: '+57-35)679-16)3((8',
            lastName: 'aliqua',
            nif: 'tempor voluptate',
            email: 'FWhNKA21@YSoJrzxoyTskbriKUs.au',
        },
        {
            nif: 'commodo mollit labore ad laborum',
            phone: '+849-1',
            email: 'TZJW@OFJyXj.dcyd',
            username: 'deserunt in',
            firstName: 'do',
            lastName2: 'irure',
            id: '31c40a30-3b80-816f-ca8d-5dd96f2ee403',
            lastName: 'est cupidatat',
        },
        {
            lastName: 'ea anim dolore',
            phone: '+3-07+7-439-13994)445061',
            nif: 'Duis velit nulla',
            id: '44ab0a74-db24-91a4-9bbe-3173b208beb0',
            username: 'velit enim minim',
            firstName: 'nostrud voluptate amet quis dolore',
            email: 'hLMMh@FxbDiOhJeSZArcsZxZcpymoKoCnftXEV.tqow',
            lastName2: 'quis exercitation esse',
        },
        {
            id: '554498e8-e43e-e8e2-9669-b028cbc4cc21',
            firstName: 'veniam',
            username: 'aliquip nulla veniam',
            lastName2: 'anim est',
            lastName: 'minim',
            nif: 'reprehenderit commodo aute eu nostrud',
            email: 'xd8jy@B.umpj',
            phone: '+1-))231(+',
        },
        {
            lastName: 'eiusmod voluptate velit',
            id: 'ac1ab48d-1a5e-2eb4-ca3d-90db917c5676',
            email: 'dKcMEc@TNVoExzfIYihe.owu',
            phone: '+31-+1917(514-36-4-((-22-61)2',
            nif: 'incididunt adipisicing in',
            firstName: 'sit veniam voluptate dolor occaecat',
            username: 'incididunt ea Lorem exercitation Duis',
            lastName2: 'sed adipisicing in veniam quis',
        },
        {
            nif: 'voluptate ex',
            lastName2: 'aliqua non Excepteur id elit',
            firstName: 'aliquip',
            id: 'e50294c6-00f8-fba6-9ccd-6207b8e76f85',
            lastName: 'sunt minim officia',
            email: 'YsqleIZK8jS@wtAjDyMcNG.sb',
            phone: '+4-)6398(88+)68788301+7199',
            username: 'labore in nulla',
        },
        {
            phone: '+517-+971(()()01+7+)(98(37335',
            lastName: 'ex ad',
            firstName: 'Excepteur aliquip est',
            username: 'esse',
            nif: 'aliqua amet sunt',
            id: '884f3007-d224-b548-c1b5-1ce782fca7f7',
            lastName2: 'sit',
            email: 'RMZ@KIOPXvDKmTdzeMGFoaHYWi.xglc',
        },
        {
            nif: 'occaecat in amet cupidatat',
            id: '1b82ad4f-f48d-9225-dad5-a573e158649a',
            firstName: 'amet',
            lastName2: 'non qui magna',
            phone: '+332-2+)(2018',
            username: 'Duis enim incididunt dolor',
            email: 'IVJd4dz0bZ@yVYiwBVQQ.sv',
            lastName: 'in in sint',
        },
        {
            id: 'b445ca19-b8d3-612d-f54b-832548b1564d',
            email: 'eQz6R-Ef97yL@pNmAJQJOOYxXzzLqnjyxcDHI.mnvz',
            nif: 'reprehenderit id culpa',
            lastName2: 'laborum sit',
            username: 'in laboris Ut ut',
            phone: '+572-(-81007',
            lastName: 'in Ut deserunt',
            firstName: 'id consequat reprehenderit ad',
        },
    ])
}

export function deleteUser(userId: string) {
    return Promise.resolve()
}

export function createUser(user: Omit<User, 'id'>) {
    return Promise.resolve()
}

export function updateUser(user: User) {
    return Promise.resolve()
}

export function getUser(userId: string) {
    return Promise.resolve({
        nif: 'occaecat in amet cupidatat',
        id: userId,
        firstName: 'amet',
        lastName2: 'non qui magna',
        phone: '+332-2+)(2018',
        username: 'Duis enim incididunt dolor',
        email: 'IVJd4dz0bZ@yVYiwBVQQ.sv',
        lastName: 'in in sint',
    })
}
